<?php

/**
 * Implementation of hook_hosting_queues().
 *
 * Return a list of queues that this module needs to manage.
 */
function hosting_task_gc_hosting_queues() {
  $result = hosting_task_gc_count_sites();
  $row = db_fetch_object($result);
  $count = $row->num_sites;
  $result2 = hosting_task_gc_count_platforms();
  $row2 = db_fetch_object($result2);
  $count2 = $row->num_platforms;
  $queue['task_gc'] = array(
    'name' => t('Task GC'),
    'description' => t('Process the garbage collection of task logs.'),
    'type' => 'batch',  # run queue sequentially. always with the same parameters.
    'frequency' => strtotime("1 hour", 0),
    'min_threads' => 6,
    'max_threads' => 12,
    'threshold' => 100,
    'total_items' => $count + $count2,
    'singular' => t('site/platform'),
    'plural' => t('sites/platforms'),
  );
  return $queue;
}

/**
 * The main queue callback for the backups.
 */
function hosting_task_gc_queue($count) {
  global $user;
  $old_user = $user;
  $user = user_load(1);
  $result = hosting_task_gc_list_sites();
  while ($site = db_fetch_object($result)) {
    node_delete($site->nid);
  }
  $result2 = hosting_task_gc_list_platforms();
  while ($platform = db_fetch_object($result2)) {
    node_delete($platform->nid);
  }
  $user = $old_user;
  $query = "SELECT DISTINCT h.vid FROM {hosting_task_log} h LEFT OUTER JOIN {node_revisions} n ON h.vid = n.vid WHERE n.vid IS NULL LIMIT 100";
  $result = db_query($query);
  while ($revision = db_fetch_object($result)) {
    $query = "DELETE FROM {hosting_task_log} WHERE vid = %d";
    db_query($query, $revision->vid);
    $num = db_affected_rows();
    watchdog('hosting_task_gc', 'Deleted @num orphaned task log entries with vid @vid.', array('@num' => $num, '@vid' => $revision->vid));
  }
}

function hosting_task_gc_list_sites() {
  $query = "SELECT DISTINCT s.nid FROM {hosting_site} s WHERE s.status = %d LIMIT 5";
  return db_query($query, HOSTING_SITE_DELETED);
}

function hosting_task_gc_list_platforms() {
  $query = "SELECT DISTINCT p.nid FROM {hosting_platform} p WHERE p.status = %d LIMIT 5";
  return db_query($query, HOSTING_PLATFORM_DELETED);
}

function hosting_task_gc_count_sites() {
  $query = "SELECT COUNT(DISTINCT s.nid) AS num_sites FROM {hosting_site} s WHERE s.status = %d";
  return db_query($query, HOSTING_SITE_DELETED);
}

function hosting_task_gc_count_platforms() {
  $query = "SELECT COUNT(DISTINCT p.nid) AS num_platforms FROM {hosting_platform} p WHERE p.status = %d";
  return db_query($query, HOSTING_PLATFORM_DELETED);
}
